version: '3.6'
services:
  nspectr:
    container_name: nspectr
    command: serve
    environment:
      PORT: 8080
      LOG_LEVEL: debug
      CERTS_PATH: /certs
    image: nspectr:latest
    ports:
    - 8080:8080
    volumes:
    - ./certs:/certs
