version: '3.6'
services:
  nspectr:
    container_name: nspectr
    command: proxy
    environment:
      PORT: 7100
      LOG_LEVEL: debug
      BACKEND_ADDR: echo:5678
    image: rms1000watt/nspectr:latest
    ports:
    - 7100:7100
    volumes:
    - ./certs:/certs

  echo:
    container_name: echo
    command: -text="hello world"
    image: hashicorp/http-echo
    ports:
    - 5678:5678
